application: subwaykl
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: noop

- url: /apple-touch-icon.png
  static_files: img/apple-touch-icon.png
  upload: noop
  
- url: /klsubway.jpg
  static_files: img/klsubway.jpg
  upload: noop

- url: /images
  static_dir: img

- url: /robots.txt
  static_files: media/robots.txt
  upload: noop

- url: /humans.txt
  static_files: media/humans.txt
  upload: noop

- url: /js
  static_dir: js

- url: /js/libs
  static_dir: js/libs

- url: /css
  static_dir: css

# The root URL (/) is handled by the index.py script. No other URLs match this pattern.
- url: /
  script: index.py

# The URL /index.html is also handled by the index.py script.
- url: /index\.html
  script: index.py
  
- url: /gavin
  script: gavin.py

# All other URLs use the not_found.py script.
- url: /.*
  script: not_found.py

